#服务端口号
server:
  port: 8901
#服务名称
spring:
  application:
    name: server

eureka:
  instance:
    hostname: localhost
  client:
    #注册中心不需要注册自己，这两处默认值是true，我们设为false
    register-with-eureka: false
    #注册中心不需要去发现服务
    fetch-registry: false
    #设置服务注册中心的URL，此处则表示为http://localhost:8901/eureka/
    serviceUrl:
      defaultZone:  http://${eureka.instance.hostname}:${server.port}/eureka/
